before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - flags:
      - -buildmode=exe
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - CC=$PWD/gencc.sh
      - CXX=$PWD/gencpp.sh
    main: ./main.go
    ldflags:
     - -s -w -X github.com/cloudquery/cloudquery/cmd.Version={{.Version}} -X github.com/cloudquery/cloudquery/cmd.Commit={{.Commit}} -X github.com/cloudquery/cloudquery/cmd.Date={{.Date}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
archives:
  -
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
